"use client";
import React from "react";
import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

interface Props {
  explanation: string | null;
  isLoading?: boolean;
}

export function ExplanationPanel({ explanation, isLoading }: Props) {
  return (
    <div style={{ padding: "2rem", height: "100%", overflowY: "auto" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "1.5rem" }}>
        <Sparkles size={18} style={{ color: "var(--color-accent)" }} />
        <h3 style={{ margin: 0, fontSize: "var(--text-base)", fontWeight: 600, color: "var(--color-accent)", fontFamily: "var(--font-mono)", letterSpacing: "0.05em" }}>
          AI EXPLANATION
        </h3>
      </div>

      {isLoading ? (
        <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
          {[1, 2, 3].map(i => (
            <motion.div key={i} animate={{ opacity: [0.3, 0.7, 0.3] }} transition={{ repeat: Infinity, duration: 1.5, delay: i * 0.2 }}
              style={{ height: "1rem", background: "rgba(178,213,229,0.1)", borderRadius: "4px", width: i === 3 ? "60%" : "100%" }} />
          ))}
        </div>
      ) : explanation ? (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
          <div style={{ background: "rgba(178,213,229,0.04)", border: "1px solid rgba(178,213,229,0.15)", borderRadius: "var(--radius-md)", padding: "1.5rem" }}>
            <p style={{ margin: 0, fontSize: "var(--text-lg)", color: "rgba(255,255,255,0.9)", lineHeight: 1.7, fontStyle: "italic" }}>
              "{explanation}"
            </p>
          </div>
          <div style={{ marginTop: "1.5rem", padding: "1rem", background: "rgba(255,255,255,0.02)", borderRadius: "var(--radius-sm)", border: "1px solid rgba(255,255,255,0.06)" }}>
            <p style={{ margin: 0, fontSize: "var(--text-sm)", color: "var(--color-text-muted)" }}>
              ✦ This explanation was generated by Gemini 2.5 Flash based on your intent and the compiled workflow graph.
            </p>
          </div>
        </motion.div>
      ) : (
        <div style={{ color: "var(--color-text-faint)", fontFamily: "var(--font-mono)", fontSize: "var(--text-sm)" }}>
          [NO EXPLANATION AVAILABLE — DEPLOY A WORKFLOW FIRST]
        </div>
      )}
    </div>
  );
}
