"use client";

import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, Terminal, Bot, Zap, Shield, Cpu } from "lucide-react";

export default function AgentsPage() {
  const [agents, setAgents] = useState<any[]>([]);

  useEffect(() => {
    // Load generated agents from memory
    const savedAgents = localStorage.getItem("autoflow_agents");
    if (savedAgents) {
      try {
        const parsed = JSON.parse(savedAgents);
        // Ensure uniqueness by name in case of duplicates from multiple runs
        const uniqueAgents = parsed.filter((v: any, i: number, a: any[]) => a.findIndex(t => (t.name === v.name)) === i);
        setAgents(uniqueAgents);
      } catch (e) {
        console.error("Failed to parse agents from local storage");
      }
    }
  }, []);

  return (
    <div style={{
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      backgroundColor: "var(--color-bg)",
      color: "var(--color-text)",
    }}>
      
      {/* Top Navbar */}
      <header style={{
        padding: "1.5rem 3rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: "1px solid rgba(178, 213, 229, 0.1)",
        background: "rgba(0, 0, 0, 0.5)",
        backdropFilter: "blur(10px)",
        position: "sticky",
        top: 0,
        zIndex: 50
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
          <Terminal style={{ color: "var(--color-accent)" }} />
          <h1 style={{ margin: 0, fontSize: "1.5rem", fontWeight: 700, letterSpacing: "-0.02em" }}>
            AutoFlow<span style={{ color: "var(--color-accent)" }}>.</span>AgentFleet
          </h1>
        </div>

        <Link href="/dashboard" passHref style={{ textDecoration: "none" }}>
          <motion.button
            whileHover={{ x: -5 }}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "0.5rem",
              background: "transparent",
              border: "none",
              color: "rgba(255,255,255,0.7)",
              cursor: "pointer",
              fontFamily: "monospace",
              fontSize: "0.9rem"
            }}
          >
            <ArrowLeft size={16} /> RETURN TO DASHBOARD
          </motion.button>
        </Link>
      </header>

      {/* Main Content */}
      <main style={{ padding: "4rem 3rem", maxWidth: "1200px", margin: "0 auto", width: "100%" }}>
        
        <div style={{ marginBottom: "3rem", display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
          <div>
            <h2 style={{ fontSize: "2.5rem", margin: 0, fontWeight: 600 }}>Active Agents</h2>
            <p style={{ color: "rgba(255,255,255,0.6)", marginTop: "0.5rem", fontSize: "1.1rem" }}>
              The specialized AI personas generated by your workflow orchestration.
            </p>
          </div>
          <div style={{ 
            background: "rgba(178, 213, 229, 0.1)", 
            padding: "0.5rem 1rem", 
            borderRadius: "50px",
            border: "1px solid rgba(178, 213, 229, 0.3)",
            fontFamily: "monospace",
            color: "var(--color-accent)",
            display: "flex",
            alignItems: "center",
            gap: "0.5rem"
          }}>
            <Cpu size={16} />
            {agents.length} AGENTS DEPLOYED
          </div>
        </div>

        {agents.length === 0 ? (
          <div style={{ 
            padding: "4rem", 
            textAlign: "center", 
            background: "rgba(178, 213, 229, 0.02)", 
            borderRadius: "12px",
            border: "1px dashed rgba(178, 213, 229, 0.2)"
          }}>
            <Bot size={48} style={{ color: "rgba(255,255,255,0.2)", margin: "0 auto 1rem auto" }} />
            <h3 style={{ fontSize: "1.2rem", color: "rgba(255,255,255,0.5)" }}>No agents detected in memory.</h3>
            <p style={{ color: "rgba(255,255,255,0.3)", marginTop: "0.5rem" }}>Deploy a workflow from the homepage to spawn specialized agents.</p>
          </div>
        ) : (
          <div style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
            gap: "1.5rem"
          }}>
            {agents.map((agent, idx) => (
              <motion.div 
                key={agent.id || idx}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.1 }}
                whileHover={{ y: -5, boxShadow: "0 10px 30px rgba(178, 213, 229, 0.1)" }}
                style={{
                  background: "rgba(5, 10, 15, 0.8)",
                  border: "1px solid rgba(178, 213, 229, 0.15)",
                  borderRadius: "12px",
                  padding: "2rem",
                  display: "flex",
                  flexDirection: "column",
                  gap: "1rem",
                  position: "relative",
                  overflow: "hidden"
                }}
              >
                {/* Status Indicator */}
                <div style={{ position: "absolute", top: "1rem", right: "1rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
                  <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#0f0", boxShadow: "0 0 10px #0f0" }} />
                  <span style={{ fontSize: "0.7rem", fontFamily: "monospace", color: "#0f0" }}>ONLINE</span>
                </div>

                <div style={{ 
                  width: "48px", 
                  height: "48px", 
                  borderRadius: "12px", 
                  background: "rgba(178, 213, 229, 0.1)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "var(--color-accent)"
                }}>
                  <Bot size={24} />
                </div>

                <div>
                  <h3 style={{ margin: 0, fontSize: "1.3rem", fontWeight: 600 }}>{agent.name}</h3>
                  <div style={{ 
                    display: "inline-block",
                    background: "rgba(255,255,255,0.05)",
                    padding: "0.2rem 0.6rem",
                    borderRadius: "4px",
                    fontSize: "0.75rem",
                    color: "rgba(255,255,255,0.6)",
                    fontFamily: "monospace",
                    marginTop: "0.5rem",
                    border: "1px solid rgba(255,255,255,0.1)"
                  }}>
                    ROLE: {agent.role.toUpperCase()}
                  </div>
                  <p style={{ margin: "1rem 0 0 0", color: "rgba(255,255,255,0.7)", fontSize: "0.95rem", lineHeight: 1.5 }}>
                    {agent.description}
                  </p>
                </div>
                
                <div style={{ marginTop: "auto", paddingTop: "1.5rem", display: "flex", gap: "0.5rem" }}>
                  <div style={{ 
                    flex: 1, 
                    display: "flex", 
                    alignItems: "center", 
                    justifyContent: "center", 
                    gap: "0.5rem",
                    padding: "0.6rem", 
                    background: "rgba(255,255,255,0.03)", 
                    borderRadius: "6px",
                    fontSize: "0.8rem",
                    color: "rgba(255,255,255,0.4)"
                  }}>
                    <Zap size={14} /> IDLE
                  </div>
                  <div style={{ 
                    flex: 1, 
                    display: "flex", 
                    alignItems: "center", 
                    justifyContent: "center", 
                    gap: "0.5rem",
                    padding: "0.6rem", 
                    background: "rgba(255,255,255,0.03)", 
                    borderRadius: "6px",
                    fontSize: "0.8rem",
                    color: "rgba(255,255,255,0.4)"
                  }}>
                    <Shield size={14} /> SECURE
                  </div>
                </div>

              </motion.div>
            ))}
          </div>
        )}

      </main>
    </div>
  );
}
